variables:
- template: pipeline-templates/global-variables.yml

trigger:
  branches:
    include:
    - main
    - release-*
  tags:
    include:
    - 'v*'
  paths:
    exclude:
    - '**/*.md'
    - LICENSE
    - NOTICE
    - docs/
    - .github/CODEOWNERS

pr:
  branches:
    include:
    - main
    - release-*
  paths:
    exclude:
    - '**/*.md'
    - LICENSE
    - NOTICE
    - docs/
    - .github/CODEOWNERS

stages:
- stage: PRAndCI
  displayName: 'PR/CI validation'
  jobs:
  - template: pipeline-templates/go-ci-job.yml
    parameters:
      jobName: GoValidation
      displayName: 'Validate safeguard-go SDK'
